// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyEBCN8D4OBhJ5fF3AfG4MtbfbV3Lwe8Q',
    appId: '1:308795588138:web:2f43ef195bb1b8f0decd53',
    messagingSenderId: '308795588138',
    projectId: 'uddyogi',
    authDomain: 'uddyogi.firebaseapp.com',
    databaseURL:
        'https://uddyogi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uddyogi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB00JFFDWQfEKRFpz50RLfKTuz9Ve4uuyg',
    appId: '1:308795588138:android:c1d07583777a1b0cdecd53',
    messagingSenderId: '308795588138',
    projectId: 'uddyogi',
    databaseURL:
        'https://uddyogi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uddyogi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOpihroNZYF0VAgWqRRMoq03l2a6A_-U',
    appId: '1:308795588138:ios:eb7cb46d4e012290decd53',
    messagingSenderId: '308795588138',
    projectId: 'uddyogi',
    databaseURL:
        'https://uddyogi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uddyogi.firebasestorage.app',
    iosBundleId: 'com.example.uddoygi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWOpihroNZYF0VAgWqRRMoq03l2a6A_-U',
    appId: '1:308795588138:ios:eb7cb46d4e012290decd53',
    messagingSenderId: '308795588138',
    projectId: 'uddyogi',
    databaseURL:
        'https://uddyogi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uddyogi.firebasestorage.app',
    iosBundleId: 'com.example.uddoygi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyEBCN8D4OBhJ5fF3AfG4MtbfbV3Lwe8Q',
    appId: '1:308795588138:web:a1b217cde47ac1cadecd53',
    messagingSenderId: '308795588138',
    projectId: 'uddyogi',
    authDomain: 'uddyogi.firebaseapp.com',
    databaseURL:
        'https://uddyogi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uddyogi.firebasestorage.app',
  );
}

