// lib/features/common/salary_screen.dart
//
// My Salary — universal screen for ALL departments
// (marketing, factory, rnd, admin, hr)
//
// Data sources (merged, deduped by period):
//   1. data/{cid}/payrolls  — payroll records generated by HR
//   2. data/{cid}/payslips  — payslips sent by HR after disbursement
//
// Lookup strategy (most reliable first):
//   A. employeeUid == currentUser.uid
//   B. email / officeEmail == realEmail (from local storage, strips +CID suffix)
//
// This ensures every department employee sees their salary regardless of
// how their account was created or which email field HR used.
// ─────────────────────────────────────────────────────────────────────────────
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:uddoygi/services/db.dart';
import 'package:uddoygi/services/local_storage_service.dart';

// ── Palette ───────────────────────────────────────────────────────────────────
const Color _green   = Color(0xFF25BC5F);
const Color _greenDk = Color(0xFF065F46);
const Color _greenLt = Color(0xFFD1FAE5);
const Color _blue    = Color(0xFF2563EB);
const Color _blueLt  = Color(0xFFEFF6FF);
const Color _orange  = Color(0xFFF97316);
const Color _red     = Color(0xFFDC2626);
const Color _bg      = Color(0xFFF7F9FC);
const Color _card    = Color(0xFFFFFFFF);
const Color _border  = Color(0x14000000);
const Color _fg      = Color(0xFF0F172A);
const Color _muted   = Color(0xFF94A3B8);

class SalaryScreen extends StatefulWidget {
  const SalaryScreen({super.key});

  @override
  State<SalaryScreen> createState() => _SalaryScreenState();
}

class _SalaryScreenState extends State<SalaryScreen>
    with SingleTickerProviderStateMixin {
  String _cid       = '';
  String _uid       = '';
  String _realEmail = ''; // real email (not the +CID namespaced auth email)

  bool _loading = true;
  String? _error;

  // Merged data from both payrolls + payslips
  List<_SalaryEntry> _entries = [];

  late final TabController _tab;
  final _money = NumberFormat.currency(locale: 'en', symbol: '৳', decimalDigits: 0);

  @override
  void initState() {
    super.initState();
    _tab = TabController(length: 2, vsync: this);
    _init();
  }

  @override
  void dispose() {
    _tab.dispose();
    super.dispose();
  }

  // ── Resolve identity ──────────────────────────────────────────────────────
  Future<void> _init() async {
    try {
      final cid = await LocalStorageService.getSavedCompanyId();
      final session = await LocalStorageService.getSession();
      final user = FirebaseAuth.instance.currentUser;

      if (cid == null || cid.isEmpty) {
        if (mounted) setState(() { _loading = false; _error = 'Company ID not found. Please log in again.'; });
        return;
      }

      final uid = user?.uid ?? '';
      // Real email: prefer session email (never namespaced), fall back to
      // stripping the +CID suffix from Firebase Auth email
      String realEmail = (session?['email'] as String?)?.trim() ?? '';
      if (realEmail.isEmpty && user?.email != null) {
        realEmail = _stripCidSuffix(user!.email!, cid);
      }

      if (mounted) {
        setState(() {
          _cid       = cid;
          _uid       = uid;
          _realEmail = realEmail;
          _loading   = false;
        });
      }
    } catch (e) {
      if (mounted) setState(() { _loading = false; _error = e.toString(); });
    }
  }

  /// Strips the +CID suffix from a namespaced auth email.
  /// e.g. "john+12345678@gmail.com" → "john@gmail.com"
  static String _stripCidSuffix(String authEmail, String cid) {
    final marker = '+$cid@';
    final idx = authEmail.indexOf(marker);
    if (idx < 0) return authEmail;
    final local  = authEmail.substring(0, idx);
    final domain = authEmail.substring(idx + marker.length);
    return '$local@$domain';
  }

  double _num(dynamic v) {
    if (v == null) return 0;
    if (v is num) return v.toDouble();
    if (v is String) return double.tryParse(v.replaceAll(',', '')) ?? 0;
    return 0;
  }

  String _formatDate(dynamic ts) {
    if (ts == null) return '—';
    final dt = ts is Timestamp ? ts.toDate() : DateTime.tryParse(ts.toString());
    if (dt == null) return '—';
    return DateFormat('d MMM yyyy').format(dt);
  }

  // ── Build streams ─────────────────────────────────────────────────────────

  /// Stream payroll records for this employee.
  /// Tries UID first; if empty falls back to email.
  Stream<List<_SalaryEntry>> _payrollStream() {
    if (_cid.isEmpty) return const Stream.empty();

    Query<Map<String, dynamic>> q;
    if (_uid.isNotEmpty) {
      q = DB.colSync(_cid, C.payrolls)
          .where('employeeUid', isEqualTo: _uid)
          .orderBy('generatedAt', descending: true);
    } else if (_realEmail.isNotEmpty) {
      q = DB.colSync(_cid, C.payrolls)
          .where('officeEmail', isEqualTo: _realEmail)
          .orderBy('generatedAt', descending: true);
    } else {
      return const Stream.empty();
    }

    return q.snapshots().map((snap) => snap.docs.map((d) {
          final m = d.data();
          return _SalaryEntry(
            id:        d.id,
            source:    'payroll',
            period:    (m['period'] ?? '').toString(),
            gross:     _num(m['grossSalary']),
            bonus:     _num(m['bonus']),
            loan:      _num(m['loanDeduction'] ?? m['loanDeductionTotal']),
            net:       _num(m['netSalary']),
            status:    (m['status'] ?? 'pending').toString(),
            method:    (m['paymentMethod'] ?? '').toString(),
            generatedAt: m['generatedAt'],
            disbursedAt: m['disbursedAt'],
            sentAt:      m['sentAt'],
            extras:    (m['extraDeductions'] as List?)?.cast<Map>() ?? [],
            dept:      (m['department'] ?? '').toString(),
          );
        }).toList());
  }

  /// Stream payslips sent by HR for this employee.
  Stream<List<_SalaryEntry>> _payslipStream() {
    if (_cid.isEmpty) return const Stream.empty();

    Query<Map<String, dynamic>> q;
    if (_uid.isNotEmpty) {
      q = DB.colSync(_cid, 'payslips')
          .where('employeeUid', isEqualTo: _uid)
          .orderBy('sentAt', descending: true);
    } else if (_realEmail.isNotEmpty) {
      q = DB.colSync(_cid, 'payslips')
          .where('officeEmail', isEqualTo: _realEmail)
          .orderBy('sentAt', descending: true);
    } else {
      return const Stream.empty();
    }

    return q.snapshots().map((snap) => snap.docs.map((d) {
          final m = d.data();
          return _SalaryEntry(
            id:        d.id,
            source:    'payslip',
            period:    (m['period'] ?? '').toString(),
            gross:     _num(m['grossSalary']),
            bonus:     _num(m['bonus']),
            loan:      _num(m['loanDeduction']),
            net:       _num(m['netSalary']),
            status:    'disbursed', // payslips are always disbursed
            method:    (m['paymentMethod'] ?? '').toString(),
            generatedAt: m['disbursedAt'],
            disbursedAt: m['disbursedAt'],
            sentAt:      m['sentAt'],
            extras:    (m['extraDeductions'] as List?)?.cast<Map>() ?? [],
            dept:      (m['department'] ?? '').toString(),
          );
        }).toList());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _bg,
      appBar: AppBar(
        elevation: 0,
        backgroundColor: _greenDk,
        foregroundColor: Colors.white,
        title: Text('My Salary',
            style: GoogleFonts.inter(fontWeight: FontWeight.w800, fontSize: 17)),
        flexibleSpace: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              colors: [Color(0xFF25BC5F), Color(0xFF065F46)],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
          ),
        ),
        bottom: TabBar(
          controller: _tab,
          indicatorColor: Colors.white,
          indicatorWeight: 3,
          labelStyle: GoogleFonts.inter(fontWeight: FontWeight.w700, fontSize: 13),
          unselectedLabelStyle: GoogleFonts.inter(fontWeight: FontWeight.w500, fontSize: 13),
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white60,
          tabs: const [
            Tab(icon: Icon(Icons.receipt_long_rounded, size: 16), text: 'Payslips'),
            Tab(icon: Icon(Icons.history_rounded, size: 16), text: 'Payroll History'),
          ],
        ),
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator(color: _green))
          : _error != null
              ? _ErrorView(message: _error!)
              : TabBarView(
                  controller: _tab,
                  children: [
                    _PayslipsTab(
                      stream: _payslipStream(),
                      money: _money,
                      formatDate: _formatDate,
                      num: _num,
                    ),
                    _PayrollHistoryTab(
                      stream: _payrollStream(),
                      money: _money,
                      formatDate: _formatDate,
                      num: _num,
                    ),
                  ],
                ),
    );
  }
}

// ── Data model ────────────────────────────────────────────────────────────────
class _SalaryEntry {
  final String id, source, period, status, method, dept;
  final double gross, bonus, loan, net;
  final dynamic generatedAt, disbursedAt, sentAt;
  final List<Map> extras;

  const _SalaryEntry({
    required this.id,
    required this.source,
    required this.period,
    required this.gross,
    required this.bonus,
    required this.loan,
    required this.net,
    required this.status,
    required this.method,
    required this.generatedAt,
    required this.disbursedAt,
    required this.sentAt,
    required this.extras,
    required this.dept,
  });
}

// ── Tab 1: Payslips (sent by HR) ──────────────────────────────────────────────
class _PayslipsTab extends StatelessWidget {
  final Stream<List<_SalaryEntry>> stream;
  final NumberFormat money;
  final String Function(dynamic) formatDate;
  final double Function(dynamic) num;

  const _PayslipsTab({
    required this.stream,
    required this.money,
    required this.formatDate,
    required this.num,
  });

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<List<_SalaryEntry>>(
      stream: stream,
      builder: (_, snap) {
        if (snap.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator(color: _green));
        }
        if (snap.hasError) {
          return _ErrorView(message: snap.error.toString());
        }
        final entries = snap.data ?? [];
        if (entries.isEmpty) {
          return const _EmptyState(
            icon: Icons.receipt_long_rounded,
            title: 'No payslips yet',
            subtitle: 'Your payslips will appear here once HR sends them after payroll is disbursed.',
          );
        }

        // Summary
        double totalNet = 0;
        for (final e in entries) { totalNet += e.net; }

        return ListView(
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 32),
          children: [
            _SummaryHero(
              totalNet: totalNet,
              count: entries.length,
              label: 'Total Received',
              money: money,
            ),
            const SizedBox(height: 16),
            ...entries.map((e) => _PayslipCard(
                  entry: e,
                  money: money,
                  formatDate: formatDate,
                )),
          ],
        );
      },
    );
  }
}

// ── Tab 2: Payroll History ────────────────────────────────────────────────────
class _PayrollHistoryTab extends StatelessWidget {
  final Stream<List<_SalaryEntry>> stream;
  final NumberFormat money;
  final String Function(dynamic) formatDate;
  final double Function(dynamic) num;

  const _PayrollHistoryTab({
    required this.stream,
    required this.money,
    required this.formatDate,
    required this.num,
  });

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<List<_SalaryEntry>>(
      stream: stream,
      builder: (_, snap) {
        if (snap.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator(color: _green));
        }
        if (snap.hasError) {
          return _ErrorView(message: snap.error.toString());
        }
        final entries = snap.data ?? [];
        if (entries.isEmpty) {
          return const _EmptyState(
            icon: Icons.payments_outlined,
            title: 'No payroll records',
            subtitle: 'Your payroll records will appear here once HR generates them.',
          );
        }

        // Summary stats
        double totalNet = 0, paidNet = 0, pendingNet = 0;
        int paidCount = 0, pendingCount = 0;
        for (final e in entries) {
          totalNet += e.net;
          if (e.status == 'disbursed') { paidNet += e.net; paidCount++; }
          else { pendingNet += e.net; pendingCount++; }
        }

        return ListView(
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 32),
          children: [
            _SummaryHero(
              totalNet: totalNet,
              count: entries.length,
              label: 'Total Payroll',
              money: money,
              subStats: [
                _SubStat(label: 'Paid', value: money.format(paidNet), count: paidCount, color: _green),
                _SubStat(label: 'Pending', value: money.format(pendingNet), count: pendingCount, color: _orange),
              ],
            ),
            const SizedBox(height: 16),
            ...entries.map((e) => _PayrollCard(
                  entry: e,
                  money: money,
                  formatDate: formatDate,
                )),
          ],
        );
      },
    );
  }
}

// ── Summary Hero ──────────────────────────────────────────────────────────────
class _SubStat {
  final String label, value;
  final int count;
  final Color color;
  const _SubStat({required this.label, required this.value, required this.count, required this.color});
}

class _SummaryHero extends StatelessWidget {
  final double totalNet;
  final int count;
  final String label;
  final NumberFormat money;
  final List<_SubStat> subStats;

  const _SummaryHero({
    required this.totalNet,
    required this.count,
    required this.label,
    required this.money,
    this.subStats = const [],
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFF25BC5F), Color(0xFF065F46)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: _green.withValues(alpha: 0.3),
            blurRadius: 16,
            offset: const Offset(0, 6),
          ),
        ],
      ),
      padding: const EdgeInsets.all(20),
      child: Stack(
        children: [
          Positioned(
            right: -16, top: -16,
            child: Container(
              width: 90, height: 90,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: Colors.white.withValues(alpha: 0.06),
              ),
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(label,
                  style: GoogleFonts.inter(
                      color: Colors.white.withValues(alpha: 0.8),
                      fontSize: 13,
                      fontWeight: FontWeight.w500)),
              const SizedBox(height: 6),
              Text(money.format(totalNet),
                  style: GoogleFonts.inter(
                      color: Colors.white,
                      fontSize: 34,
                      fontWeight: FontWeight.w800,
                      letterSpacing: -0.5)),
              const SizedBox(height: 4),
              Text('$count month${count != 1 ? 's' : ''}',
                  style: GoogleFonts.inter(
                      color: Colors.white.withValues(alpha: 0.7),
                      fontSize: 12)),
              if (subStats.isNotEmpty) ...[
                const SizedBox(height: 14),
                Row(
                  children: subStats.map((s) => Expanded(
                    child: Container(
                      margin: EdgeInsets.only(
                          right: s == subStats.last ? 0 : 8),
                      padding: const EdgeInsets.symmetric(
                          horizontal: 12, vertical: 10),
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.12),
                        borderRadius: BorderRadius.circular(10),
                        border: Border.all(
                            color: Colors.white.withValues(alpha: 0.2)),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(s.value,
                              style: GoogleFonts.inter(
                                  color: Colors.white,
                                  fontWeight: FontWeight.w800,
                                  fontSize: 14)),
                          const SizedBox(height: 2),
                          Text('${s.label} (${s.count})',
                              style: GoogleFonts.inter(
                                  color: Colors.white.withValues(alpha: 0.7),
                                  fontSize: 11)),
                        ],
                      ),
                    ),
                  )).toList(),
                ),
              ],
            ],
          ),
        ],
      ),
    );
  }
}

// ── Payslip Card (from payslips collection — sent by HR) ──────────────────────
class _PayslipCard extends StatefulWidget {
  final _SalaryEntry entry;
  final NumberFormat money;
  final String Function(dynamic) formatDate;

  const _PayslipCard({
    required this.entry,
    required this.money,
    required this.formatDate,
  });

  @override
  State<_PayslipCard> createState() => _PayslipCardState();
}

class _PayslipCardState extends State<_PayslipCard> {
  bool _expanded = false;

  @override
  Widget build(BuildContext context) {
    final e = widget.entry;

    return Container(
      margin: const EdgeInsets.only(bottom: 14),
      decoration: BoxDecoration(
        color: _card,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: _green.withValues(alpha: 0.2), width: 1.5),
        boxShadow: const [
          BoxShadow(color: Color(0x08000000), blurRadius: 8, offset: Offset(0, 2)),
        ],
      ),
      child: Column(
        children: [
          // Header
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
            child: Row(children: [
              Container(
                width: 44, height: 44,
                decoration: BoxDecoration(
                  color: _greenLt,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Icon(Icons.receipt_long_rounded,
                    color: _greenDk, size: 22),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(e.period,
                        style: GoogleFonts.inter(
                            fontWeight: FontWeight.w800,
                            fontSize: 15, color: _fg)),
                    const SizedBox(height: 2),
                    Text(
                      'Sent ${widget.formatDate(e.sentAt)}',
                      style: GoogleFonts.inter(color: _muted, fontSize: 12),
                    ),
                  ],
                ),
              ),
              // Paid badge
              Container(
                padding: const EdgeInsets.symmetric(
                    horizontal: 10, vertical: 5),
                decoration: BoxDecoration(
                  color: _greenLt,
                  borderRadius: BorderRadius.circular(99),
                  border: Border.all(color: _green.withValues(alpha: 0.4)),
                ),
                child: Row(mainAxisSize: MainAxisSize.min, children: [
                  const Icon(Icons.check_circle_rounded,
                      size: 11, color: _green),
                  const SizedBox(width: 4),
                  Text('Paid',
                      style: GoogleFonts.inter(
                          color: _greenDk,
                          fontWeight: FontWeight.w700,
                          fontSize: 11)),
                ]),
              ),
            ]),
          ),

          const SizedBox(height: 14),

          // Net pay hero
          Container(
            margin: const EdgeInsets.symmetric(horizontal: 16),
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFF25BC5F), Color(0xFF065F46)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Net Pay',
                        style: GoogleFonts.inter(
                            color: Colors.white.withValues(alpha: 0.8),
                            fontSize: 12)),
                    const SizedBox(height: 4),
                    Text(widget.money.format(e.net),
                        style: GoogleFonts.inter(
                            color: Colors.white,
                            fontSize: 28,
                            fontWeight: FontWeight.w800,
                            letterSpacing: -0.5)),
                  ],
                ),
                if (e.method.isNotEmpty)
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 10, vertical: 6),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.15),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(e.method,
                        style: GoogleFonts.inter(
                            color: Colors.white,
                            fontWeight: FontWeight.w700,
                            fontSize: 12)),
                  ),
              ],
            ),
          ),

          const SizedBox(height: 12),

          // Gross / Bonus / Deduction row
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Row(children: [
              _SummaryCell(label: 'GROSS',
                  value: widget.money.format(e.gross), color: _fg),
              _SummaryCell(
                  label: 'BONUS',
                  value: e.bonus > 0
                      ? '+${widget.money.format(e.bonus)}'
                      : '৳0',
                  color: e.bonus > 0 ? _green : _muted),
              _SummaryCell(
                  label: 'DEDUCTION',
                  value: e.loan > 0
                      ? '-${widget.money.format(e.loan)}'
                      : '৳0',
                  color: e.loan > 0 ? _red : _muted),
            ]),
          ),

          // Expand toggle
          InkWell(
            onTap: () => setState(() => _expanded = !_expanded),
            borderRadius: const BorderRadius.vertical(
                bottom: Radius.circular(16)),
            child: Padding(
              padding: const EdgeInsets.symmetric(
                  horizontal: 16, vertical: 10),
              child: Row(children: [
                Text(_expanded ? 'Hide details' : 'View details',
                    style: GoogleFonts.inter(
                        color: _blue,
                        fontWeight: FontWeight.w600,
                        fontSize: 13)),
                const SizedBox(width: 4),
                Icon(
                  _expanded
                      ? Icons.keyboard_arrow_up_rounded
                      : Icons.keyboard_arrow_down_rounded,
                  color: _blue, size: 18,
                ),
              ]),
            ),
          ),

          // Expanded detail
          if (_expanded) ...[
            const Divider(height: 1, color: _border),
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 14, 16, 14),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _DetailRow(label: 'Base Salary',
                      value: widget.money.format(e.gross), color: _fg),
                  if (e.bonus > 0)
                    _DetailRow(label: 'Bonus',
                        value: '+${widget.money.format(e.bonus)}',
                        color: _green),
                  if (e.loan > 0 || e.extras.isNotEmpty) ...[
                    const SizedBox(height: 8),
                    Text('Deductions',
                        style: GoogleFonts.inter(
                            fontWeight: FontWeight.w700,
                            fontSize: 13, color: _fg)),
                    const SizedBox(height: 6),
                  ],
                  if (e.loan > 0)
                    _DetailRow(label: 'Loan EMI',
                        value: '-${widget.money.format(e.loan)}',
                        color: _red),
                  ...e.extras.map((ex) => _DetailRow(
                        label: (ex['label'] ?? 'Deduction').toString(),
                        value: '-${widget.money.format(
                            double.tryParse(ex['amount']?.toString() ?? '0') ?? 0)}',
                        color: _orange,
                      )),
                  const SizedBox(height: 8),
                  const Divider(height: 1, color: _border),
                  const SizedBox(height: 8),
                  _DetailRow(label: 'Net Pay',
                      value: widget.money.format(e.net),
                      color: _green, bold: true),
                  if (e.disbursedAt != null) ...[
                    const SizedBox(height: 8),
                    Row(children: [
                      const Icon(Icons.schedule_rounded,
                          size: 12, color: _muted),
                      const SizedBox(width: 4),
                      Text(
                        'Disbursed ${widget.formatDate(e.disbursedAt)}',
                        style: GoogleFonts.inter(
                            color: _muted, fontSize: 11),
                      ),
                    ]),
                  ],
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}

// ── Payroll Card (from payrolls collection — HR-generated) ────────────────────
class _PayrollCard extends StatefulWidget {
  final _SalaryEntry entry;
  final NumberFormat money;
  final String Function(dynamic) formatDate;

  const _PayrollCard({
    required this.entry,
    required this.money,
    required this.formatDate,
  });

  @override
  State<_PayrollCard> createState() => _PayrollCardState();
}

class _PayrollCardState extends State<_PayrollCard> {
  bool _expanded = false;

  @override
  Widget build(BuildContext context) {
    final e = widget.entry;

    Color statusColor;
    String statusLabel;
    IconData statusIcon;
    switch (e.status) {
      case 'disbursed':
        statusColor = _green;
        statusLabel = 'Paid';
        statusIcon  = Icons.check_circle_rounded;
        break;
      case 'requested':
        statusColor = _orange;
        statusLabel = 'Processing';
        statusIcon  = Icons.hourglass_top_rounded;
        break;
      default:
        statusColor = _muted;
        statusLabel = 'Pending';
        statusIcon  = Icons.schedule_rounded;
    }

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: _card,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
          color: e.status == 'disbursed'
              ? _green.withValues(alpha: 0.2)
              : _border,
        ),
        boxShadow: const [
          BoxShadow(color: Color(0x06000000), blurRadius: 6, offset: Offset(0, 2)),
        ],
      ),
      child: Column(
        children: [
          // Header row
          Padding(
            padding: const EdgeInsets.fromLTRB(14, 14, 14, 0),
            child: Row(children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(e.period,
                        style: GoogleFonts.inter(
                            fontWeight: FontWeight.w800,
                            fontSize: 15, color: _fg)),
                    const SizedBox(height: 2),
                    Text(
                      'Generated ${widget.formatDate(e.generatedAt)}',
                      style: GoogleFonts.inter(
                          color: _muted, fontSize: 11),
                    ),
                  ],
                ),
              ),
              // Net amount
              Column(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  Text(widget.money.format(e.net),
                      style: GoogleFonts.inter(
                          fontWeight: FontWeight.w800,
                          fontSize: 16,
                          color: e.status == 'disbursed' ? _green : _fg)),
                  const SizedBox(height: 4),
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 8, vertical: 3),
                    decoration: BoxDecoration(
                      color: statusColor.withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(99),
                      border: Border.all(
                          color: statusColor.withValues(alpha: 0.3)),
                    ),
                    child: Row(mainAxisSize: MainAxisSize.min, children: [
                      Icon(statusIcon, size: 10, color: statusColor),
                      const SizedBox(width: 3),
                      Text(statusLabel,
                          style: GoogleFonts.inter(
                              fontSize: 10,
                              fontWeight: FontWeight.w700,
                              color: statusColor)),
                    ]),
                  ),
                ],
              ),
            ]),
          ),

          const SizedBox(height: 10),

          // Breakdown row
          Container(
            margin: const EdgeInsets.symmetric(horizontal: 14),
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
            decoration: BoxDecoration(
              color: _bg,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Row(children: [
              _SummaryCell(label: 'GROSS',
                  value: widget.money.format(e.gross), color: _fg),
              _SummaryCell(
                  label: 'BONUS',
                  value: e.bonus > 0
                      ? '+${widget.money.format(e.bonus)}'
                      : '৳0',
                  color: e.bonus > 0 ? _green : _muted),
              _SummaryCell(
                  label: 'DEDUCTION',
                  value: e.loan > 0
                      ? '-${widget.money.format(e.loan)}'
                      : '৳0',
                  color: e.loan > 0 ? _red : _muted),
            ]),
          ),

          // Expand toggle
          InkWell(
            onTap: () => setState(() => _expanded = !_expanded),
            borderRadius: const BorderRadius.vertical(
                bottom: Radius.circular(14)),
            child: Padding(
              padding: const EdgeInsets.symmetric(
                  horizontal: 14, vertical: 10),
              child: Row(children: [
                Text(_expanded ? 'Hide details' : 'View details',
                    style: GoogleFonts.inter(
                        color: _blue,
                        fontWeight: FontWeight.w600,
                        fontSize: 12)),
                const SizedBox(width: 4),
                Icon(
                  _expanded
                      ? Icons.keyboard_arrow_up_rounded
                      : Icons.keyboard_arrow_down_rounded,
                  color: _blue, size: 16,
                ),
              ]),
            ),
          ),

          if (_expanded) ...[
            const Divider(height: 1, color: _border),
            Padding(
              padding: const EdgeInsets.fromLTRB(14, 12, 14, 14),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _DetailRow(label: 'Base Salary',
                      value: widget.money.format(e.gross), color: _fg),
                  if (e.bonus > 0)
                    _DetailRow(label: 'Bonus',
                        value: '+${widget.money.format(e.bonus)}',
                        color: _green),
                  if (e.loan > 0)
                    _DetailRow(label: 'Loan Deduction',
                        value: '-${widget.money.format(e.loan)}',
                        color: _red),
                  ...e.extras.map((ex) => _DetailRow(
                        label: (ex['label'] ?? 'Deduction').toString(),
                        value: '-${widget.money.format(
                            double.tryParse(ex['amount']?.toString() ?? '0') ?? 0)}',
                        color: _orange,
                      )),
                  const SizedBox(height: 8),
                  const Divider(height: 1, color: _border),
                  const SizedBox(height: 8),
                  _DetailRow(label: 'Net Pay',
                      value: widget.money.format(e.net),
                      color: _green, bold: true),
                  if (e.status == 'disbursed' && e.disbursedAt != null) ...[
                    const SizedBox(height: 6),
                    Row(children: [
                      const Icon(Icons.check_circle_rounded,
                          size: 12, color: _green),
                      const SizedBox(width: 4),
                      Text(
                        'Paid on ${widget.formatDate(e.disbursedAt)}'
                        '${e.method.isNotEmpty ? ' via ${e.method}' : ''}',
                        style: GoogleFonts.inter(
                            color: _green, fontSize: 11,
                            fontWeight: FontWeight.w600),
                      ),
                    ]),
                  ],
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}

// ── Shared widgets ────────────────────────────────────────────────────────────
class _SummaryCell extends StatelessWidget {
  final String label, value;
  final Color color;
  const _SummaryCell(
      {required this.label, required this.value, required this.color});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Column(children: [
        Text(label,
            style: GoogleFonts.inter(
                color: _muted, fontSize: 9,
                fontWeight: FontWeight.w700, letterSpacing: 0.5)),
        const SizedBox(height: 3),
        FittedBox(
          child: Text(value,
              style: GoogleFonts.inter(
                  fontWeight: FontWeight.w700, fontSize: 13, color: color)),
        ),
      ]),
    );
  }
}

class _DetailRow extends StatelessWidget {
  final String label, value;
  final Color color;
  final bool bold;
  const _DetailRow({
    required this.label,
    required this.value,
    required this.color,
    this.bold = false,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label,
              style: GoogleFonts.inter(
                  color: bold ? _fg : _muted,
                  fontSize: 13,
                  fontWeight: bold ? FontWeight.w700 : FontWeight.w500)),
          Text(value,
              style: GoogleFonts.inter(
                  color: color, fontSize: 13,
                  fontWeight: bold ? FontWeight.w800 : FontWeight.w700)),
        ],
      ),
    );
  }
}

class _EmptyState extends StatelessWidget {
  final IconData icon;
  final String title, subtitle;
  const _EmptyState(
      {required this.icon, required this.title, required this.subtitle});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          Container(
            width: 72, height: 72,
            decoration: BoxDecoration(
              color: _green.withValues(alpha: 0.08),
              borderRadius: BorderRadius.circular(20),
            ),
            child: Icon(icon, size: 34, color: _green),
          ),
          const SizedBox(height: 16),
          Text(title,
              style: GoogleFonts.inter(
                  fontWeight: FontWeight.w800, fontSize: 16, color: _fg)),
          const SizedBox(height: 6),
          Text(subtitle,
              textAlign: TextAlign.center,
              style: GoogleFonts.inter(color: _muted, fontSize: 13, height: 1.5)),
        ]),
      ),
    );
  }
}

class _ErrorView extends StatelessWidget {
  final String message;
  const _ErrorView({required this.message});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          const Icon(Icons.error_outline_rounded, size: 40, color: _red),
          const SizedBox(height: 12),
          Text('Could not load salary data',
              style: GoogleFonts.inter(
                  fontWeight: FontWeight.w700, fontSize: 15, color: _fg)),
          const SizedBox(height: 6),
          Text(message,
              textAlign: TextAlign.center,
              style: GoogleFonts.inter(color: _muted, fontSize: 12)),
        ]),
      ),
    );
  }
}
